# Model arguments
model_name_or_path: allenai/OLMo-7B-0724-hf
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
use_liger_kernel: true
tokenizer_name_or_path: gartland/finewebedu-196K-tokenizer      ## this is the tokenizer. Should be changed (e.g. gartland/finewebedu_24K_tokenizer)
# Data training arguments
dataset_name: gartland/finewebedu-196K-tokenized               ## this is the tokenized dataset. should be change (e.g. gartland/finewebedu_24K_tokenized)
dataset_split: 
- train
dataset_file_list: 
  - "train-00-of-10.parquet"
  - "train-01-of-10.parquet"
  - "train-02-of-10.parquet"
  - "train-03-of-10.parquet"
  - "train-04-of-10.parquet"
  - "train-05-of-10.parquet"
  - "train-06-of-10.parquet"
  - "train-07-of-10.parquet"
  - "train-08-of-10.parquet"
  - "train-09-of-10.parquet"
  - "train-10-of-10.parquet"
  - "train-11-of-10.parquet"
  - "train-12-of-10.parquet"
  - "train-13-of-10.parquet"
  - "train-14-of-10.parquet"
  - "train-15-of-10.parquet"
  - "train-16-of-10.parquet"
  - "train-17-of-10.parquet"
  - "train-18-of-10.parquet"
  - "train-19-of-10.parquet"
  - "train-20-of-10.parquet"
  - "train-21-of-10.parquet"
  - "train-22-of-10.parquet"
  - "train-23-of-10.parquet"
  - "train-24-of-10.parquet"
  - "train-25-of-10.parquet"
  - "train-26-of-10.parquet"
  - "train-27-of-10.parquet"
  - "train-28-of-10.parquet"
  - "train-29-of-10.parquet"
  - "train-30-of-10.parquet"
  - "train-31-of-10.parquet"
  - "train-32-of-10.parquet"
  - "train-33-of-10.parquet"
  - "train-34-of-10.parquet"
  - "train-35-of-10.parquet"
  - "train-36-of-10.parquet"
  - "train-37-of-10.parquet"
  - "train-38-of-10.parquet"
  - "train-39-of-10.parquet"
  - "train-40-of-10.parquet"
  - "train-41-of-10.parquet"
  - "train-42-of-10.parquet"

cache_dir: 
preprocessing_num_workers: 32
auto_insert_empty_system_msg: true
dataloader_num_workers: 16

# Trainer config
bf16: true
tf32: true
torch_compile: false
do_eval: false
gradient_accumulation_steps: 1                                                      ## 24K:4, 49K:8, 98K:8, 196K:16  
gradient_checkpointing: false
# gradient_checkpointing_kwargs:
#   use_reentrant: False
#hub_model_id: gartland/finewebedu-196K-unembdnorm                                    ## will not be uploaded on huggingface
learning_rate: 6.0e-4                                                                 ## use this as fixed lr
log_level: info 
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine
max_steps: -1
num_train_epochs: 1
output_dir: output_196K_embdnorm                                                                   ## always change name of output_dir when running each experiment
overwrite_output_dir: true
per_device_train_batch_size: 32                                                      ## 24K:8, 49K:4, 98K:4, 196K:2
remove_unused_columns: true
report_to: wandb ## change to 'wandb' if you use wandb
save_strategy: "steps"
save_steps: 200
save_total_limit: 3

seed: 42
warmup_steps: 700
weight_decay: 0.1

# Hub
push_to_hub: false
hub_private_repo: true

# WandB
wandb_entity: 
wandb_project:
run_name: ## finewebedu-vocabsize-base
