# Model arguments
model_name_or_path: allenai/OLMo-7B-0724-hf
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
use_liger_kernel: true

# Data training arguments
dataset_name: pico-lm/pretokenized-dolma
dataset_split: 
- train
preprocessing_num_workers: 32
auto_insert_empty_system_msg: true
dataloader_num_workers: 16

# Trainer config
bf16: true
tf32: true
torch_compile: false
do_eval: false
gradient_accumulation_steps: 1
gradient_checkpointing: false
# gradient_checkpointing_kwargs:
#   use_reentrant: False
hub_model_id: Cambridge-KAIST/SmolLM-14m-Dolma-v0.1-Proposed
learning_rate: 3.0e-3
log_level: info
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: warmup_stable_decay
max_steps: -1
num_train_epochs: 1
output_dir: output
overwrite_output_dir: true
per_device_train_batch_size: 1024
remove_unused_columns: true
report_to: none
save_strategy: "steps"
save_steps: 25

seed: 42
warmup_steps: 1000
weight_decay: 0.1

# Hub
push_to_hub: false
hub_private_repo: true

# WandB
wandb_entity: ### Your WandB entity
wandb_project: ### Your WandB project 
run_name: SmolLM-14m-Dolma-v0.1-Proposed